version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=confeitaria_emanuelnerys
      - DB_USERNAME=postgres
      - DB_PASSWORD=123emanuel

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: confeitaria_emanuelnerys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123emanuel
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
